name: CI

on:
  push:
  pull_request:

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: docker build -t app:${{ github.sha }} .

      - name: Scan & push to TrivyHub
        uses: theo-mrn/trivy_dashboard/.github/actions/trivy-push@main
        with:
          image: app:${{ github.sha }}
          api-key: ${{ vars.DASHBOARD_API_KEY }}
